<?php
class region {

    // printable name
    public $name = NULL; 

    // id for db look up
    public $id = NULL;

    // region info
    public $isCapital = NULL; 
    public $isPort = NULL;
    public $totalSlots = NULL; //can be autogenerated from port/capital
    public $standardSlots = NULL; //can be autogenerated from port/capital
    public $trade = NULL;

    //slot classes (figure out how to have class as part of class)

    function returnTotalSlots (){

        if ($this->$isCapital && $this->$isPort) {return 6;}
        if ($this->$isCapital && !$this->$isPort) {return 5;}
        if (!$this->$isCapital && $$this->isPort) {return 4;}
        if (!$this->$isCapital && !$this->$isPort) {return 3;}
    }

    function returnStandardSlots (){

        if ($this->$isCapital && $$this->isPort) {return 4;}
        if ($this->$isCapital && !$this->$isPort) {return 4;}
        if (!$this->$isCapital && $this->$isPort) {return 3;}
        if (!$this->$isCapital && !$this->$isPort) {return 3;}
    }
} 

?>