<?php
class region {

    // printable name
    public $name = NULL; 

    // id for db look up
    public $id = NULL;

    // region info
    public $isCapital = NULL; 
    public $isPort = NULL;
    public $totalSlots = NULL; //can be autogenerated from port/capital
    public $standardSlots = NULL; //can be autogenerated from port/capital
    public $trade = NULL;

    public function generateSlots ()
    {
    	for ($i=0; $i < $this->totalSlots; $i++) { 
    		
    		$this->{'slot'.$i} = new slot();
    	}
    }

    public function returnTotalSlots (){

        if ($this->isCapital){
        	if ($this->isPort){
        		return 6;
        	}
        	else{
        		return 5;
        	}
        }
        else{
        	if ($this->isPort){
        		return 5;
        	}
        	else{
        		return 4;
        	}
        }
    }

    public function returnStandardSlots (){

        if ($this->isCapital){
        	if ($this->isPort){
        		return 4;
        	}
        	else{
        		return 4;
        	}
        }
        else{
        	if ($this->isPort){
        		return 3;
        	}
        	else{
        		return 3;
        	}
        }
    }
} 

?>